---
title: "Jesús Olivares' website"
author: "Jesús Olivares Jabalera"
date: "4/11/2021"
output:
  html_document:
    theme: readable
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About

I have received my education in Sport Sciences at the University of Granada, in which I coursed my Bachelors degree and Master course in Research in Physical Activity and Sport Sciences.

Currently, I am a PhD student in the field of ACL injury prevention in football (soccer) and working as a sport scientist at FSI-GD Estoril Praia.

## Interests

* Sports performance
* Injury prevention
* Sports biomechanics
* Data analytics

## Projects

* I am learning programming in R, so my first project in this platform is the creation of this website, which hopefully will allow me to share my personal and professional information with people around the world.

## Profiles 

* [LinkedIn](https://www.linkedin.com/in/jes%C3%BAs-olivares-jabalera-413b84159/)
* ...
* [GitHub](http://github.com/JesusOlivaresJ)

## Contact

* [jesusyolivares@gmail.com](mailto:jesusyolivares@gmail.com)
